# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a453743bac2dfca1f0e8712e98c255cd"
name = "Biypod"
application_url = "https://app.biypod.com"
embedded = true
handle = "biypod"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://jxuycozeiepqhndbvjto.supabase.co/functions/v1/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://jxuycozeiepqhndbvjto.supabase.co/functions/v1/webhooks"

  # MANDATORY GDPR COMPLIANCE WEBHOOKS
  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "https://jxuycozeiepqhndbvjto.supabase.co/functions/v1/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "https://jxuycozeiepqhndbvjto.supabase.co/functions/v1/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "https://jxuycozeiepqhndbvjto.supabase.co/functions/v1/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_themes,write_themes,read_publications,write_publications"

[auth]
redirect_urls = ["https://app.biypod.com/auth/callback", "https://app.biypod.com/auth/shopify/callback", "https://app.biypod.com/api/auth/callback"]

[pos]
embedded = false
